/**
 * OpenApi Spezifikation for GeekHR-Connect
 * API Dokumentation für die Spring Boot Anwendung
 *
 * Contact: asmitterand@yahoo.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Link } from './link';


export interface EntityModelEmployee { 
    gender?: EntityModelEmployee.GenderEnum;
    firstName?: string;
    lastName?: string;
    email?: string;
    phone?: string;
    city?: string;
    country?: string;
    dateOfBirth?: string;
    remainingVacationDays?: number;
    onVacation?: boolean;
    position?: EntityModelEmployee.PositionEnum;
    _links?: { [key: string]: Link; };
}
export namespace EntityModelEmployee {
    export type GenderEnum = 'MEN' | 'WOMEN';
    export const GenderEnum = {
        Men: 'MEN' as GenderEnum,
        Women: 'WOMEN' as GenderEnum
    };
    export type PositionEnum = 'CEO' | 'CTO' | 'COO' | 'TEAM_MANAGER_SOFTWARE' | 'SENIOR_SOFTWARE_DEVELOPER' | 'SOFTWARE_DEVELOPER' | 'JUNIOR_SOFTWARE_DEVELOPER' | 'WORKING_STUDENT';
    export const PositionEnum = {
        Ceo: 'CEO' as PositionEnum,
        Cto: 'CTO' as PositionEnum,
        Coo: 'COO' as PositionEnum,
        TeamManagerSoftware: 'TEAM_MANAGER_SOFTWARE' as PositionEnum,
        SeniorSoftwareDeveloper: 'SENIOR_SOFTWARE_DEVELOPER' as PositionEnum,
        SoftwareDeveloper: 'SOFTWARE_DEVELOPER' as PositionEnum,
        JuniorSoftwareDeveloper: 'JUNIOR_SOFTWARE_DEVELOPER' as PositionEnum,
        WorkingStudent: 'WORKING_STUDENT' as PositionEnum
    };
}


