/**
 * OpenApi Spezifikation for GeekHR-Connect
 * API Dokumentation für die Spring Boot Anwendung
 *
 * Contact: asmitterand@yahoo.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PageMetadata } from './pageMetadata';
import { PagedModelEntityModelEmployeeEmbedded } from './pagedModelEntityModelEmployeeEmbedded';
import { EmployeeResponse } from './employeeResponse';
import { Link } from './link';
import { PagedModelEntityModelEmployee } from './pagedModelEntityModelEmployee';


/**
 * @type GetCollectionResourceEmployeeGet11200Response
 * @export
 */
export type GetCollectionResourceEmployeeGet11200Response = Array<EmployeeResponse> | PagedModelEntityModelEmployee;

