/**
 * OpenApi Spezifikation for GeekHR-Connect
 * API Dokumentation für die Spring Boot Anwendung
 *
 * Contact: asmitterand@yahoo.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EntityModelEmployee } from './entityModelEmployee';
import { EmployeeResponse } from './employeeResponse';
import { Link } from './link';


/**
 * @type GetItemResourceEmployeeGet1200Response
 * @export
 */
export type GetItemResourceEmployeeGet1200Response = EmployeeResponse | EntityModelEmployee;

