/**
 * OpenApi Spezifikation for GeekHR-Connect
 * API Dokumentation für die Spring Boot Anwendung
 *
 * Contact: asmitterand@yahoo.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Link { 
    href?: string;
    hreflang?: string;
    title?: string;
    type?: string;
    deprecation?: string;
    profile?: string;
    name?: string;
    templated?: boolean;
}

