/**
 * OpenApi Spezifikation for GeekHR-Connect
 * API Dokumentation für die Spring Boot Anwendung
 *
 * Contact: asmitterand@yahoo.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PageMetadata } from './pageMetadata';
import { PagedModelEntityModelEmployeeEmbedded } from './pagedModelEntityModelEmployeeEmbedded';
import { Link } from './link';


export interface PagedModelEntityModelEmployee { 
    _embedded?: PagedModelEntityModelEmployeeEmbedded;
    _links?: { [key: string]: Link; };
    page?: PageMetadata;
}

